name: Check versions and urls
on: 
  push:
  pull_request:
  schedule:
  - cron: "0 */6 * * *"

jobs:
  check:
    name: Check Urls and Versions
    runs-on: windows-latest
    env:
      SCOOP: 'C:\Scoop\user'
    steps:
    - uses: actions/checkout@v2

    - name: Install Scoop
      run: |
        iwr get.scoop.sh -outfile 'install.ps1'
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned
        .\install.ps1 -RunAsAdmin
        echo "$env:SCOOP\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Check Urls
      run: |
        # Scripts are using Write-Host making them tricky to handle
        # Running once for the logs, once for error handling
        .\bin\checkurls.ps1
        .\bin\checkurls.ps1 6> results.txt
        $error_string = Select-String -Path results.txt -Pattern "error"
        if ($error_string -ne $null) {
            Exit 1
        }
    - name: Check Versions
      run: |
        # Scripts are using Write-Host making them tricky to handle
        # Running once for the logs, once for error handling
        .\bin\checkver.ps1
        .\bin\checkver.ps1 6> results.txt
        $error_string = Select-String -Path results.txt -Pattern "(scoop version is|error)"
        if ($error_string -ne $null) {
            Exit 1
        }
